import Image from "next/image";
import styles from "../styles/About.module.scss";

import Head from "next/head";
import Footer from "../components/footer.jsx";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>About</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}></main>

            <Footer />
        </div>
    );
}
